#pragma once

#include "ascendc/host_api/tiling/template_argument.h"

#define SPARSE_SOFTMAX_FP32 0
#define SPARSE_SOFTMAX_FP16 1
#define SPARSE_SOFTMAX_BF16 2

ASCENDC_TPL_ARGS_DECL(SparseSoftmax,
    ASCENDC_TPL_DTYPE_DECL(DT_MODE,
        SPARSE_SOFTMAX_FP32,
        SPARSE_SOFTMAX_FP16,
        SPARSE_SOFTMAX_BF16),
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(DT_MODE, SPARSE_SOFTMAX_FP32),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(DT_MODE, SPARSE_SOFTMAX_FP16),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(DT_MODE, SPARSE_SOFTMAX_BF16),
    ),
);
